name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run units tests and generate coverage
        run: npx nyc mocha

      - name: Run cypress test, integration and UI
        run: npx cypress run --spec "cypress/e2e/*.spec.js,cypress/e2e/front.spec.js"

